### ISSUE TITLE
Navigate to Home page

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#113]
Write the code to navigate to home page after user has logged in/ sign up in the app.

_Happy Contributing!!!😊_

**Comment by shoaib-31** [comment]
Claim

**Comment by AngadManroy** [comment]
Claim

**Comment by kushal7201** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @AngadManroy

**Comment by AngadManroy** [comment]
Just a small query, there's no firebase integrated i supppse and no authentication process. is the expectation that the login button when clicked redirects us to the home page?

**Comment by muffinboy19** [comment]
no for now just redirect it to blankActivity as the project will progress the homeactivity will be created , about the firebase yes it needs to be integrarted

**Comment by muffinboy19** [comment]
@AngadManroy  your deadline is over
