### ISSUE TITLE
Add transitions

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#114]
Add transitions/animations on the following pages while transitioning between them:-

- login -> sign up
- sign up -> login
- sign up -> home
- log in -> home

_Happy contributing !!!😊_

**Comment by AngadManroy** [comment]
Claim

**Comment by kushal7201** [comment]
claim

**Comment by QuantTitan** [comment]
Claim

**Comment by VertikaBajpai** [comment]
Claim

**Comment by insanecoder02** [comment]
assigned to @kushal7201
