### ISSUE TITLE
Short Term Memory

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#116]
Add a forgot password option on Login Activity to avoid any password loss in future😁

_Happy Contributing!!! 😊_

**Comment by Rohit-110** [comment]
c

**Comment by kushal7201** [comment]
claim

**Comment by QuantTitan** [comment]
Claim

**Comment by VertikaBajpai** [comment]
Claim

**Comment by insanecoder02** [comment]
assigned to @Rohit-110

**Comment by muffinboy19** [comment]
issue is completed by @Rohit-110
