### ISSUE TITLE
Redirected to home

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#117]
write the logic if the user has **already logged in the app** then everytime they opens the app, they should be **re-directed to the home🏠** page rather than every time logging in the app.

**Also follow the clean Architecture**

_Happy Contribution!!! 😊_

**Comment by kushal7201** [comment]
claim

**Comment by VertikaBajpai** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @VertikaBajpai
