### ISSUE TITLE
A Buggy code!!! here we go again😣

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#120]
This is the worst task😒 we developers hate!!! Yeah **Debugging the code**

So in this task you have to resolve the errors☠️ which _May/Maynot be_ there in code

whether in pubspec.yaml or any .dart file

You have to find on your own😂

Good luck Debugger, May you find your peace😉
**You have my respect**🫡

**Comment by tonyStark-Jr** [comment]
claim

**Comment by Rohit-110** [comment]
c

**Comment by anshuman-rai-27** [comment]
C

**Comment by Nandinig24** [comment]
C

**Comment by insanecoder02** [comment]
assigned to @Rohit-110 
Gud luck bro

**Comment by insanecoder02** [comment]
@Rohit-110 plz submit the task before 2:00 pm today
so that new issues can go live

**Comment by muffinboy19** [comment]
@Nandinig24  why did you comment C ?

**Comment by Nandinig24** [comment]
It is for claim thar i posted
