### ISSUE TITLE
Re-design The Splash Screen 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#128]
**Issue: Redesign Splash Screen**

🎨 **Description:**
Current splash screen design isn't final. Redesign to match provided image. 

⏰ **Deadline:**
2 days from assignment.

🚀 **Happy Contributing!**
![Rectangle 4159](https://github.com/opencodeiiita/Donation-App/assets/87519281/656c798f-1942-4700-82ad-2039c854ea98)

**Comment by VertikaBajpai** [comment]
Claim
