### ISSUE TITLE
Create to 2 Screens  

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#129]
**Issue: Create Identical Pages from Given Image**

🖼️ **Task:**
Develop two pages to replicate the design in the provided images. These screens should appear consecutively after the splash screen.

⏰ **Deadline:**
2 days from assignment.

🎨 **Guidelines:**
- Ensure pixel-perfect replication.
- Use the same color scheme and layout.

🚀 **Happy Contributing!**

---

Page 1: ![Image](https://github.com/opencodeiiita/Donation-App/assets/87519281/f17c8696-a63d-47f9-ac4e-dc1723e3c976)

Page 2: ![Image](https://github.com/opencodeiiita/Donation-App/assets/87519281/3cb097b2-aa09-404b-8f9f-b78b71ca3f59)

**Comment by Rohit-110** [comment]
Claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by muffinboy19** [comment]
assgined to @rnavaneeth992

**Comment by SharkyBytes** [comment]
Claim

**Comment by muffinboy19** [comment]
Reminder for @rnavaneeth992

**Comment by rnavaneeth992** [comment]
I will complete by trm evening
