### ISSUE TITLE
Task#

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#130]
**Issue: Create Identical Pages from Given Image**

🖼️ **Task:**
Develop one  page
 to replicate the design in the provided images.  Do not attach the screen after any other screen.
Also in this page the image needs to be a multiple image viewer where the images automatically rotate 

⏰ **Deadline:**
2 days from assignment.

🎨 **Guidelines:**
- Ensure pixel-perfect replication.
- Use the same color scheme and layout.

🚀 **Happy Contributing!**

---

![this](https://github.com/opencodeiiita/Donation-App/assets/87519281/47ee31f3-5e50-4762-9164-695aac24690a)

**Comment by Rohit-110** [comment]
Claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by muffinboy19** [comment]
done
