### ISSUE TITLE
Re-Desing The SignUp page

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#131]
**Issue: Update Login Screen Design**

🔐 **Task:**
Revise the login screen design based on the provided image.
Also clicking on the login text should redirect to the loginPage

📄 **Details:**
- Modify the login screen to match the new design.
- Implement new color schemes and layout elements.

🚀 **Happy Contributing!**

---
![it](https://github.com/opencodeiiita/Donation-App/assets/87519281/ce27e93b-2783-4dd7-ac25-5487a4e6ff59)

**Comment by Rohit-110** [comment]
Claim

**Comment by Rancho-rachit** [comment]
Claim

**Comment by Aastha-ojha-20** [comment]
Claim

**Comment by muffinboy19** [comment]
@Rancho-rachit  pls regiister or the issue will be reassigned

**Comment by muffinboy19** [comment]
reminder @Rancho-rachit

**Comment by DikshantK2004** [comment]
Claim

**Comment by Rancho-rachit** [comment]
#142
