### ISSUE TITLE
Design Sign-In Page Issue

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#134]
### Task Description
Your task is to carefully design the sign-in page. 🎨 Please follow the design provided diligently to ensure accurate implementation.

### Guideline

To access the individual elements present in the design, refer to the Figma link mentioned in the README file. ⏳

**Deadline for Task: 2 days** ⌛

**Happy Designing!** 🌟
---
![boop](https://github.com/opencodeiiita/Donation-App/assets/87519281/af005a9f-4920-4bb5-a0ee-fae540841cd3)

**Comment by CodinJack** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by insanecoder02** [comment]
assigned to @CodinJack
