### ISSUE TITLE
Design Feed Fragment Issue

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#135]
### Task Description
Your task is to design the feed fragment, following the provided design below. 🎨 Please omit the popular section and leave it blank.

### Guideline

To access the individual elements present in the design, refer to the Figma link mentioned in the README file. ⏳

**Deadline for Task: 2 days** ⌛

**Happy Designing!** 🌟

---
![neeos](https://github.com/opencodeiiita/Donation-App/assets/87519281/aa2df017-1b9c-4ea7-98c3-275bc4cdbf09)

**Comment by DikshantK2004** [comment]
Claim

**Comment by muffinboy19** [comment]
assigned to @DikshantK2004
