### ISSUE TITLE
Create Donation Page Issue

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#136]
### Task Description
Your task is to create a donation page where the donor can view a summary of their donation. This page should display dummy data for now, and later we will integrate Firebase fetching.

Additionally, incorporate the following features:
- Implement an image viewer to showcase multiple images related to the donation.
- Add a video viewer to allow users to watch videos associated with the donation.

Create a new page without linking it to any existing pages.

### Guideline

Design the donation page with features that include an image viewer for multiple images and a video viewer for donation-related videos. Provide a pleasant and user-friendly experience.

**Note: You can keep the description field currently empty or add dummy data as needed.**

**Deadline for Task: 2 days** ⌛

**Happy Coding!** 🌟

---
![aa](https://github.com/opencodeiiita/Donation-App/assets/87519281/0ac3821c-37f4-4b14-ad89-8ccccaeb9bee)

**Comment by rnavaneeth992** [comment]
Claim

**Comment by muffinboy19** [comment]
All the best @rnavaneeth992

**Comment by rnavaneeth992** [comment]
> All the best @rnavaneeth992

Thank You

**Comment by pahalsrivastava** [comment]
claim

**Comment by muffinboy19** [comment]
@rnavaneeth992  your deadline is over

**Comment by CodinJack** [comment]
claim

**Comment by rnavaneeth992** [comment]
> @rnavaneeth992 your deadline is over

Hi I will complete make PR by today Night

**Comment by DikshantK2004** [comment]
Claim

**Comment by rnavaneeth992** [comment]
> > @rnavaneeth992 your deadline is over
> 
> Hi I will complete make PR by today Night

@muffinboy19

**Comment by criticic** [comment]
claim

**Comment by muffinboy19** [comment]
your deadline is over  cant help @rnavaneeth992
