### ISSUE TITLE
repair #task1

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#140]
🛠️ **Tasks:**
1. **Splash Screen:**
   - Change font style to match the design.
   - Adjust text color to match the design.

2. **Screens Before GetStarted:**
   - Replace multiple image views with a collage image.
   - Change text color to match the design.

3. **GetStarted Page:**
   - Add more images to the array of imagedisplay.

4. **Buttons Design:**
   - Ensure the button design aligns with the Figma file.

**Happy Contributing!**

**Comment by pahalsrivastava** [comment]
claim

**Comment by theprocoder2367** [comment]
Claim

**Comment by muffinboy19** [comment]
@pahalsrivastava  register or we have to reassign this issue

**Comment by pahalsrivastava** [comment]
> @pahalsrivastava register or we have to reassign this issue

I have already registered at events@GeekHaven

**Comment by muffinboy19** [comment]
yeah now you can work i guess

**Comment by pahalsrivastava** [comment]
> yeah now you can work i guess

Thanks

**Comment by pahalsrivastava** [comment]
hey is there any attached code for the splash screen? or do I need to
create an entirely new one?

**Comment by muffinboy19** [comment]
@pahalsrivastava  your deadline is over now

**Comment by DikshantK2004** [comment]
Claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by theprocoder2367** [comment]
claim
