### ISSUE TITLE
Hamburger Me

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#141]
🛠️ **Tasks:**
1. **Implement Hamburger Drawer:**
   - Add a 3D-style hamburger drawer according to the provided design.
   - Ensure the drawer appears within a box.
   - All buttons within the hamburger should be functional and open respective pages.

**Note:** If you have any doubts about how to implement this, feel free to ask for assistance. We're here to help!

Important: The hamburger component is already created in the feed fragment, so utilize it for this task.

**Happy Contributing!** 🚀

**Important:** The deadline for this task is 2 days. 📅 If you have any questions or need guidance on implementing the hamburger drawer, don't hesitate to reach out! 🤝

---
![thoose](https://github.com/opencodeiiita/Donation-App/assets/87519281/b78a8828-bb56-4fa8-a59a-c69b9204156d)

**Comment by pahalsrivastava** [comment]
claim

**Comment by theprocoder2367** [comment]
Claim

**Comment by theprocoder2367** [comment]
Thankyou @muffinboy19

**Comment by muffinboy19** [comment]
https://www.youtube.com/watch?v=Z37ukFI4Ot0  
this resouces might help as the issue is not easy

**Comment by theprocoder2367** [comment]
Thankyou again @muffinboy19

**Comment by muffinboy19** [comment]
@theprocoder2367  your deadline is over i gues

**Comment by CodinJack** [comment]
claimc
