### ISSUE TITLE
Repair Me (Task-2)

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#148]
Currently some of the buttons are not working/redirecting to the desired activity

your task is to made them working.

You can take the help of [Figma file](https://www.figma.com/file/9xTKRAgvwCvi3ybLfZlqNH/OpenCode?type=design&node-id=0%3A1&mode=design&t=ClmxYtXpwdQ5Znc7-1) for the navigations

_Happy Contributing!!!_

**Comment by CodinJack** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by abhisheksharma010** [comment]
Claim

**Comment by theprocoder2367** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @abhisheksharma010

**Comment by Apoorv012** [comment]
@insanecoder02 I claimed it before Abhishek. Why was I not assigned.

**Comment by insanecoder02** [comment]
> @insanecoder02 I claimed it before Abhishek. Why was I not assigned.

You were already assigned 3 tasks that's why it's not been assigned to you.

**Comment by Apoorv012** [comment]
Ok, thank you
