### ISSUE TITLE
Signup and Login Page Issues

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#150]
## Description
I have identified several issues on the signup and login pages that need to be addressed.

### Signup Screen
- The "Continue" button is not working on the signup screen.

### Login Page
- The email box is appearing twice instead of a password box on the login page.
- The "Create Account" option is not functioning as expected.

## Expected Behavior
- The "Continue" button on the signup screen should proceed to the next step.
- The login page should have a single email box and a password box.
- The "Create Account" option should successfully create a new account.

NOTE:- The deadline for this task is only **1 day**.

_Happy contributing!!!😉_

**Comment by DikshantK2004** [comment]
Claim

**Comment by Apoorv012** [comment]
c

**Comment by kushal7201** [comment]
Claim

**Comment by muffinboy19** [comment]
closing this issue would be re publishing this issue
