### ISSUE TITLE
 Add Side Navigation Bar on Hamburger Click

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#151]
#### Description
🚀 Implement a side navigation bar that appears when clicking on the hamburger icon, following the design specifications.

#### Design
You have to follow this [Figma design](https://www.figma.com/file/9xTKRAgvwCvi3ybLfZlqNH/OpenCode?type=design&node-id=0-1&mode=design&t=5TWYC3TCEQfuai0d-0).

#### Expected Behavior
👉 When the user clicks on the hamburger icon, the side navigation bar should smoothly slide in from the left, displaying the necessary navigation links.

#### Screenshots
If applicable, include screenshots or GIFs demonstrating the current state and the proposed changes.

#### Deadline
⏰Deadline for this task is 2 days after you have assigned.

_Happy Contributing!!!_😊

**Comment by Apoorv012** [comment]
claim

**Comment by muffinboy19** [comment]
Closed for now @Apoorv012

**Comment by sarthakvermaa** [comment]
claim
