### ISSUE TITLE
who is Codin_Jack ❓ 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#152]
#### **Issue Description:**
Improve and redesign the forgot password screen to match the overall app design. Add necessary elements such as a text box for email ID, a reset button, and create a new OTP page after the reset button is pressed.

#### **Design Requirements:**

1. **Email ID Text Box:**
   - Include a text box prominently asking for the user's email ID.
   - Ensure the text box is aligned with the app's design aesthetics.

2. **Reset Button:**
   - Implement a reset button that stands out, encouraging users to initiate the password reset process.
   - Use a contrasting color or bold styling to make the button easily noticeable.

3. **New Page - OTP Page:**
   - Upon pressing the **Reset Button**, navigate users to a new page for OTP verification.
   - Design the OTP page to seamlessly flow with the app's existing visual elements.

🎨✨🔒

Happy Contributing!
---
![otp](https://github.com/opencodeiiita/Donation-App/assets/87519281/41822cf0-4db9-4d03-8cb9-898a27e82989)

**Comment by CodinJack** [comment]
claim

**Comment by theprocoder2367** [comment]
Claim

**Comment by muffinboy19** [comment]
we found CodinJack

**Comment by muffinboy19** [comment]
make a pr now @CodinJack
