### ISSUE TITLE
Profile Page Design

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#153]
#### **Task Description:**
Your task is to design the profile page according to the given specifications below. Ensure that all buttons are functional, and use sample images where required for the time being.

The design might be of different color theme but your submission should be altered to fit the current app color theme

Happy Contributing! 🎨🖌️
---
![profeo](https://github.com/opencodeiiita/Donation-App/assets/87519281/b7cb3135-b79d-4238-91a7-e8b2cadb18e0)

**Comment by theprocoder2367** [comment]
Claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by DikshantK2004** [comment]
Please unassign me from this task.

**Comment by CodinJack** [comment]
claim

**Comment by theprocoder2367** [comment]
claim

**Comment by muffinboy19** [comment]
claim

**Comment by theprocoder2367** [comment]
Misuse of power🥲

**Comment by CodinJack** [comment]
can you give me partial points for making the profile page, and give the button functionality to someone else please, as Ill be busy for some days and wont have much time

**Comment by muffinboy19** [comment]
okies

**Comment by muffinboy19** [comment]
@theprocoder2367  you want to hop on that one

**Comment by theprocoder2367** [comment]
Yes
