### ISSUE TITLE
SignMeUP!!!!!

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#154]
#### **Task Description:**
Your task is to add an extra page after the SignUp page, requesting the user to set their password. The new page should adhere to the general app design and include the following requirements:

#### **Design Specifications:**

1. **Password Setup:**
   - Include fields for both password and confirm password.
   - Implement a button allowing users to toggle between the *** state and normal state for password visibility.

2. **User Authentication:**
   - Authenticate the user using the provided email ID and password.
   - Implement this using firebase also comment your email id so that we can add you in the firebase console , to add the  functionality to verify user credentials.

4. **Redirect to BaseHomeActivity:**
   - After successful authentication, redirect the user to the BaseHomeActivity, providing a smooth transition into the main app experience.

5. **Toast Confirmation:**
   - Display a toast message confirming that the user is registered.
   - Implement a toast message upon entering the HomeScreen to enhance the user experience.

**Comment by Apoorv012** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by insanecoder02** [comment]
@Apoorv012 your deadline is near

**Comment by Apoorv012** [comment]
My work is most complete

**Comment by theprocoder2367** [comment]
claim

**Comment by Apoorv012** [comment]
@insanecoder02 Could you look at the issue I sent in the discord chat?
https://discord.com/channels/885149696249708635/1179785214478790676/1190250199432581210
