### ISSUE TITLE
SignMeINNNNNN

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#155]
#### **Enhancements:**

1. **SignIn with Email:**
   - Implement the ability for users to sign in using their email ID.
   - Utilize Firebase authentication for a secure and seamless sign-in experience.

#### **Bug Fixes:**

1. **LoginPage Styling:**
   - Adjust the excessive upper margin/padding on the LoginPage for a more visually balanced layout.
   - Resize the textBox elements to a more suitable size for improved aesthetics.

#### **Post-Authentication Actions:**

1. **Redirect to HomeActivity:**
   - Upon successful authentication, redirect the user to the HomeActivity.
   - Enhance the user experience with a smooth transition to the main app interface.

2. **Toast Confirmation:**
   - Display a toast message confirming the successful sign-in process.
   - Provide feedback to the user for a positive interaction.

**Comment by sarthakvermaa** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by insanecoder02** [comment]
@sarthakvermaa your deadline is near

**Comment by sarthakvermaa** [comment]
@insanecoder02 Right now, I'm not at home. I will be able to do PR in a couple of hours. Please consider this.

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by kushal7201** [comment]
@muffinboy19  I will try to submit the PR till midnight.

**Comment by theprocoder2367** [comment]
Claim

**Comment by criticic** [comment]
claim
