### ISSUE TITLE
DonateMeeeeee

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#156]
#### **Task Description:**
Your task this time is to enhance the FeedFragment by displaying all the donations in a ListView. Follow the instructions below to achieve this functionality:

#### **Requirements:**

1. **Donation ListView:**
   - Implement a ListView in the FeedFragment to showcase all donations.
   - The data for the ListView should be fetched from the "donations" collection in Firebase Firestore.

2. **Individual Donation Ad Design:**
   - Design the layout for individual donation ads based on the given photo 

3. **Firebase Setup:**
   - Create a new collection in Firebase Firestore named "donations."
   - Add sample documents to the "donations" collection. Each document should include properties like `addImage`, `addTitle`, `addDescription`, `addOrganisation`, `addTarget`, `addRaised`.

4. **create some sample donatios***
5.  Also the feedfragment is already created so you have to add the listview in the fragment 
---
![dd](https://github.com/opencodeiiita/Donation-App/assets/87519281/40845824-b58e-4b1b-96a2-5a44fe6de650)

**Comment by theprocoder2367** [comment]
Claim

**Comment by theprocoder2367** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by criticic** [comment]
claim
