### ISSUE TITLE
"I Am Iron Man."

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#165]
**GitHub Issue: Add SHA-1 and SHA-256 Keys for Google Login in Firebase Console** 🚀

🛠 **Task Description:**

1. **Firebase Console Configuration:**
   - 🔄 Add the SHA-1 key and SHA-256 key to the Firebase Console to enable Google login features in the app.
   - 🌐 Navigate to the Firebase project settings and locate the section for adding SHA keys.
   - 🔐 Input both the SHA-1 and SHA-256 keys securely.

**Note: If you are not registered in the Firebase Console, please DM your email ID in the GitHub comments or on Discord.**

🎉 **Happy Contributing!** Your contribution in enhancing authentication features is greatly appreciated. 🌟

for this issue you have provide your email id and then make a blank pr only those who are added in the conosle will get there pr merged

**Comment by theprocoder2367** [comment]
Claim

**Comment by muffinboy19** [comment]
you dont hav e to claim this issue 
\

**Comment by rnavaneeth992** [comment]
> **GitHub Issue: Add SHA-1 and SHA-256 Keys for Google Login in Firebase Console** 🚀
> 
> 🛠 **Task Description:**
> 
> 1. **Firebase Console Configuration:**
>    
>    * 🔄 Add the SHA-1 key and SHA-256 key to the Firebase Console to enable Google login features in the app.
>    * 🌐 Navigate to the Firebase project settings and locate the section for adding SHA keys.
>    * 🔐 Input both the SHA-1 and SHA-256 keys securely.
> 
> **Note: If you are not registered in the Firebase Console, please DM your email ID in the GitHub comments or on Discord.**
> 
> 🎉 **Happy Contributing!** Your contribution in enhancing authentication features is greatly appreciated. 🌟
> 
> for this issue you have provide your email id and then make a blank pr only those who are added in the conosle will get there pr merged

@muffinboy19 r.navaneeth992@gmail.com
