### ISSUE TITLE
Jeanne Dielman, 23, Quai du Commerce, 1080 Bruxelles (1975) 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#170]
---

🔄 **New Task: Fetching and Displaying Donation Ads**

1. 📈 **Donation Ads Collection in Firestore:**
   - Check if there is an existing collection for donation ads in Firestore. If it exists, utilize it; otherwise, create a new collection.
   - Add more dummy data to the donation ads collection to showcase a variety of ads.
   - Implement functionality to fetch and display donation ads on the main home page.

2. 🚀 **Navigation Update:**
   - Remove the bottom navigation bar to simplify the user interface.
   - Set the home page as the main landing page for a streamlined user experience.

   **Note:** Ensure that the donation ads are presented in an engaging manner, and the removal of the bottom navigation bar does not compromise the app's usability.

**Disclimer** to work on this issue you should be registred in the firebase if not then message  us for its acess

---

**Comment by Aman-iiita063** [comment]
Claim
