### ISSUE TITLE
Raiders of the Lost Ark (1981) 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#171]
---

🔄 **Code Modification and Firebase Integration:**

1. 🍔 **Hamburger Button Position:**
   - Modify the code to ensure that the hamburger button remains fixed at the top of the app and does not move down when the screen is scrolled. The button should stay at the top for a consistent user experience.

2. 📊 **User Collection in Firestore:**
   - Create a collection named "users" in Firestore to store user data.
   - For each user, add properties such as name, email id, and profile picture URL to the "users" collection.

3. 📸 **Profile Picture Handling for Email Authentication:**
   - When a user enters the app through email authentication, prompt them to provide a profile picture.
   - Implement a screen for users to capture or upload their profile picture.
   - Upon selecting or capturing a picture, upload it to the user's section in Firebase in URL format.
   - Display the same profile picture in the hamburger menu for a cohesive user experience.

   **Note:** Ensure that the modifications and additions enhance the overall user interface and maintain consistency across the app.

---

**Comment by criticic** [comment]
claim

**Comment by theprocoder2367** [comment]
Claim
