### ISSUE TITLE
La Dolce Vita (1960) 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#172]
---

🔄 **Adding New Pages and Navigation Enhancements:**

1. ➕ **Create New Fund Page:**
   - When the "Create New Fund" button is clicked (both in the hamburger menu and the home page), redirect the user to a blank page specifically designed for creating a new fund.
   - Ensure that both buttons lead to the same new page for consistency.

2. 📄 **Additional Blank Pages:**
   - Create blank pages for "Settings," "History," "Help & FAQ."
   - Include a back button on each of these pages to allow users to navigate back to the previous screen.

3. 👤 **Profile Button and Profile Page:**
   - Attach the profile button in the hamburger menu to redirect users to a dedicated profile page.
   - Ensure that the profile page displays relevant user information, possibly fetched from the Firebase "users" collection.

4. 🚪 **Logout Functionality:**
   - Implement a logout button that, when pressed, logs the user out and redirects them to the front page of the app.
   - Confirm the user's intent to logout and handle the logout process securely.

   **Note:** Focus on creating intuitive navigation and maintaining a cohesive user experience across different sections of the app.

---

**Comment by CodinJack** [comment]
claim

**Comment by theprocoder2367** [comment]
Claim

**Comment by insanecoder02** [comment]
@CodinJack make ur PR by EOD otherwise it will be assigned to someone else.

**Comment by Mannxxx** [comment]
Claim

**Comment by theprocoder2367** [comment]
Please assign me this Issue

**Comment by theprocoder2367** [comment]
The 2nd claim was mine

**Comment by insanecoder02** [comment]
@theprocoder2367 you have claimed it before the deadline was over

**Comment by DikshantK2004** [comment]
Claim

**Comment by muffinboy19** [comment]
claim now

**Comment by theprocoder2367** [comment]
Claim
