### ISSUE TITLE
Seven Samurai (1954) 7. Seven Samurai (1954) 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#173]
---

🔑 **Google Sign-In Integration:**

Your task is to implement Google Sign-In functionality using the Google button. To accomplish this, make sure you are registered on the Firebase console and obtain the necessary SHA key for your app.

1. 📱 **Google Sign-In Implementation:**
   - Integrate the Google Sign-In API with your app, allowing users to sign in using their Google credentials.
   - Ensure a seamless user experience during the authentication process.

2. 🔑 **SHA Key Addition:**
   - Obtain the SHA key for your app from the Android Studio or command line.
   - Add the SHA key to your Firebase project settings to enable Google Sign-In.

   **Note:** Ensure that the integration is secure, and users can successfully sign in using their Google accounts. This task requires registration on the Firebase console and careful handling of the SHA key.

---

**Comment by DikshantK2004** [comment]
Claim

**Comment by insanecoder02** [comment]
@DikshantK2004 make ur PR by EOD otherwise it will be assigned to someone else.

**Comment by kushal7201** [comment]
Claim
