### ISSUE TITLE
Implement Google Sign-In Feature

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#179]
- **Issue Description:** 🌐 Enhance user authentication by integrating Google Sign-In functionality.

- **Task Details:**
   - Add the Google Sign-In feature to both the signup and sign-in pages.
   - When the Google button is clicked on either page, initiate the Google Sign-In process.
   - Retrieve and store relevant user information from the Google account, such as email and profile picture.
   - Ensure a seamless transition between Google Sign-In and the respective signup or sign-in flows.
   - Test thoroughly to confirm the successful implementation of the Google Sign-In feature.

**Comment by criticic** [comment]
claim
