### ISSUE TITLE
front screens ui is not good 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#182]
#### 1. Improve Intro Screens Interaction
- **Issue Description:** 🔄 Enhance the user experience on the front screen by addressing issues with the slidable intro screens.
- **Task Details:**
   - Investigate and rectify the slidable behavior among the intro screens that adversely affects user experience.
   - Ensure a smooth and intuitive transition between intro screens without unintended slidable behavior.
   - Test the updated interaction to guarantee a seamless and user-friendly experience.

#### 2. Ensure Design Consistency for Video Screen
- **Issue Description:** 🎨 Align the design consistency of the screen displaying videos with other screens on the front page.
- **Task Details:**
   - Analyze the design of the screen showing videos and identify inconsistencies with other front screen elements.
   - Implement necessary adjustments to achieve a cohesive design across all front screens.
   - Confirm that the video screen aligns with the overall theme and visual elements used in other parts of the application.

**Comment by rnavaneeth992** [comment]
claim

**Comment by Mannxxx** [comment]
claim

**Comment by insanecoder02** [comment]
@rnavaneeth992 plz send your PR asap.
