### ISSUE TITLE
Creating screens for donation

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Donation-App#183]
#### 1. Donation History Screen
- **Issue Description:** 📜 Create a screen displaying a list of donations made by the current user.
- **Task Details:**
   - Implement functionality to fetch and display a list of donations made by the user.
   - Design a clear and user-friendly layout for the Donation History screen.
   - Ensure accurate representation of donation details, including the donation amount, date, or any additional relevant information.
   - Include appropriate navigation elements for seamless transitions.

#### 2. Donation Creation Screen
- **Issue Description:** ➕ Implement a screen with a "+ button" to facilitate making new donations.
- **Task Details:**
   - Design and implement a screen accessible from the home screen with a prominent "+ button."
   - Allow users to initiate the donation creation process by tapping the "+ button."
   - Provide a smooth transition to the Donation Creation screen.
   - Include any necessary input fields or options for creating a new donation.

#### 3. Cart Box System Screen
- **Issue Description:** 🛒 Develop a cart box system screen for users to add items and specify donation amounts.
- **Task Details:**
   - Design an intuitive and user-friendly Cart Box System screen with a focus on adding donation items.
   - Include options for users to input donation amounts and any relevant details.
   - Ensure that the Cart Box System screen aligns with the provided design specifications.
   - Implement a seamless flow for users to add items to the cart and proceed with the donation.

---
1.
![1](https://github.com/opencodeiiita/Donation-App/assets/87519281/16375fc0-d3ec-43ab-b44e-b7d757323e50)

2. 
![2](https://github.com/opencodeiiita/Donation-App/assets/87519281/1b642042-3f48-40e6-8d5c-56c551b2aebf)

**Comment by theprocoder2367** [comment]
Claim

**Comment by VrajShah34** [comment]
claim

**Comment by Mannxxx** [comment]
claim

**Comment by insanecoder02** [comment]
@VrajShah34 plz send your PR asap.

**Comment by theprocoder2367** [comment]
Claim
