### ISSUE TITLE
Design the logo

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#2]
**Design a Good Logo for the App 🎨**

- Attach📎 a screenshot/folder link of your work with your PR.
- Point🥇 will only be awarded to the PR that is accepted.

**PS: This issue is open for all, so no need to claim this issue. You can directly create a pull request
Note: This issue will be active for _only 3 days._ ⏳**

_Happy Contributing!😊_

**Comment by kushal7201** [comment]
I want ot claim the issue @muffinboy19

**Comment by insanecoder02** [comment]
there is no need to claim for this issue. this is for everyone

**Comment by Suresh12321** [comment]
Logo for Donation app

![Logo](https://github.com/opencodeiiita/Donation-App/assets/124915437/a8b31573-332e-469d-94b2-b8a8fe09cfb8)

**Comment by Suresh12321** [comment]
Issue:#2
App logo

![Logo](https://github.com/opencodeiiita/Donation-App/assets/124915437/4b033da7-059a-4b2e-aadc-ce7ad0328651)
