### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#3]
Create a Splash Screen with Transition to NextActivity 🚀

Develop a splash screen that dynamically engages users for 3 seconds before seamlessly transitioning to the NextActivity.

Ensure a visually appealing design for the splash screen to capture attention and enhance user experience. 🎨

- attach a screenshot/folder link of your work to review it easily.

**PS: This issue is open for all, so no need to claim this issue. You can directly create a pull request.
Note: This issue will be active for 3 days. ⏳**

_Happy contributing! 😊_

**Comment by Aman-iiita063** [comment]
please assign this task to me
