### ISSUE TITLE
Create Home Activity

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#4]
Create HomeActivity with Bottom Navigation Bar 🏡

Your task for this issue is to design a HomeActivity featuring a bottom navigation bar with 3 fragments:

- Feed
- Your donations
- Profile

Additionally, ensure to create three corresponding blank fragments.📝

**Note: In this issue the assignments will be on a first-come basis. Comment below to be assigned to this issue.**

_Happy contributing! 😊_

**Comment by akoolarni** [comment]
@maintainers,
assign this issue to me.

**Comment by jash-j3** [comment]
Please assign this issue to me, I'm interested to work on it.

**Comment by Samarborkar** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by muffinboy19** [comment]
issue is assgined to @akoolarni

**Comment by Aman-iiita063** [comment]
please assign this task to me

**Comment by Nandinig24** [comment]
claim

**Comment by akoolarni** [comment]
I have submitted the PR, hence unassigning myself form the task. 
Thanx

**Comment by muffinboy19** [comment]
issued is completed by @akoolarni
