### ISSUE TITLE
Create Login Activity

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Donation-App#5]
Your task for this issue is to design a Login Activtiy UI asking for

- user's email
- user's password

**PS: This issue is open for all, so no need to claim this issue. You can directly create a pull request**

_Happy contributing! 😊_

**Comment by VertikaBajpai** [comment]
Hello @insanecoder02 ,please assign me this issue.

**Comment by insanecoder02** [comment]
This issue is for everyone, so no need to claim this issue. You can directly create a pull request

**Comment by akoolarni** [comment]
@maintainers, just a doubt, through login page, the user will be routed to main/home or splash page right?

**Comment by muffinboy19** [comment]
home screen

**Comment by sanjayh-2022** [comment]
Claim

**Comment by muffinboy19** [comment]
issue is compeleted by @VertikaBajpai
